.TH vzdqcheck 8 "Mar 06, 2008" "Virtuozzo" "Containers"
.SH NAME
\fBvzdqcheck\fR \- counts disk usage
.SH SYNOPSIS
.TP
\fBvzdqcheck\fP [\fIoption\fP ...] \fIpath\fP
.SH DESCRIPTION
\fBvzdqcheck\fP summarize disk usage of all files under the \fIpath\fP.
.SH OPTIONS
.TP
.B -h
Print usage information.
.TP
.B -V
Print utility version.
.TP
.B -q
Quiet mode. Causes all warning and diagnostic messages to be suppressed.
Only fatal errors are displayed.
.TP
.B -v
Verbose mode.  Causes the utility to print debugging messages about its
progress. Multiple \fB-v\fP options increase verbosity. Maximum is 2.
.SH COPYRIGHT
Copyright (C) 2000-2007, SWsoft. Licensed under GNU GPL.
